# Generated by Django 4.2.6 on 2023-10-30 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_bio'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
